name: Screener Prompt (web_search → JSON → local charts)
on:
  workflow_dispatch:
    inputs:
      TEST_LIMIT:
        description: "Trim companies.xlsx to first N rows for a cheap test run (0 = no trim)"
        required: false
        default: "0"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RESP_MODEL: gpt-5                 # <— stays on GPT-5
      BATCH_SIZE: "20"
      # Optional cost/robustness tuning for the script:
      REQUEST_TIMEOUT: "90"             # seconds (used by OpenAI client)
      SDK_MAX_RETRIES: "2"              # short client retries
      TEST_LIMIT: ${{ inputs.TEST_LIMIT || '0' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ==== COST-SAVER DURING TESTING ====
      # If TEST_LIMIT > 0, trim the Excel to the first N rows before calling the API.
      - name: Cost-saver: optionally limit companies for test run
        run: |
          python - <<'PY'
          import os, pandas as pd
          n = int(os.getenv("TEST_LIMIT", "0"))
          if n <= 0:
              print("TEST_LIMIT=0 → no trim")
              raise SystemExit(0)
          # find Excel file
          for path in ("data/companies.xlsx", "data/companies10.xlsx"):
              if os.path.exists(path):
                  df = pd.read_excel(path)
                  trimmed = df.head(n)
                  trimmed.to_excel(path, index=False)
                  print(f"Trimmed {path} to first {n} companies for a cheap test run.")
                  break
          else:
              print("No companies.xlsx/companies10.xlsx found; skipping trim.")
          PY

      - name: Run batches
        run: python scripts/run_batches.py

      - name: List build outputs
        run: ls -la build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screener-report
          path: build/**
