name: Screener Prompt (web_search → JSON → local charts)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RESP_MODEL: gpt-5
      BATCH_SIZE: "20"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run batches
        run: python scripts/run_batches.py

      - name: List build outputs
        run: ls -la build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screener-report
          path: build/**
