name: Screener Prompt (web_search → JSON → local charts)

on:
  workflow_dispatch:
    inputs:
      TEST_LIMIT:
        description: "Trim companies.xlsx to first N rows"
        required: false
        default: "0"
        type: number  # This ensures a numeric input field appears
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RESP_MODEL: gpt-5
      BATCH_SIZE: "20"
      REQUEST_TIMEOUT: "90"
      SDK_MAX_RETRIES: "2"
      TEST_LIMIT: ${{ inputs.TEST_LIMIT }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cost-saver: optionally limit companies for test run
        run: |
          python - <<'PY'
          import os, pandas as pd
          n = int(os.getenv("TEST_LIMIT", "0"))
          if n <= 0:
              print("TEST_LIMIT=0 → no trim")
              raise SystemExit(0)
          for path in ("data/companies.xlsx", "data/companies10.xlsx"):
              if os.path.exists(path):
                  df = pd.read_excel(path)
                  df.head(n).to_excel(path, index=False)
                  print(f"Trimmed {path} to first {n} companies for a cheap test run.")
                  break
          else:
              print("No companies.xlsx/companies10.xlsx found; skipping trim.")
          PY

      - name: Run batches
        run: python scripts/run_batches.py

      - name: List build outputs
        run: ls -la build || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screener-report
          path: build/**
