name: Screener Prompt (Charts & CSV)

on:
  workflow_dispatch:
    inputs:
      TEST_LIMIT:
        type: number
        description: "Trim companies.xlsx to first N rows (0 = all)"
        default: 0

jobs:
  screener:
    name: Generate Equity Report
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RESP_MODEL: gpt-5
      BATCH_SIZE: "20"
      REQUEST_TIMEOUT: "90"
      SDK_MAX_RETRIES: "2"
      TEST_LIMIT: ${{ inputs.TEST_LIMIT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply TEST_LIMIT (cost-saver)
        if: ${{ inputs.TEST_LIMIT != 0 }}
        run: |
          python - <<'PY'
          import os, pandas as pd
          n = int(os.getenv("TEST_LIMIT", "0"))
          for path in ("data/companies.xlsx", "data/companies10.xlsx"):
              if os.path.exists(path):
                  df = pd.read_excel(path)
                  df.head(n).to_excel(path, index=False)
                  print(f"Trimmed {path} to {n} rows.")
                  break
          else:
              print("No companies.xlsx/companies10.xlsx found.")
          PY

      - name: Run Python batches
        run: python scripts/run_batches.py

      - name: Show build outputs
        run: ls -R build || true

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screener-report
          path: build/**
