name: Screener Prompt Batches (5 at a time)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai pandas
      - name: Run prompt batches
        run: |
          python scripts/run_batches.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screener-batch-report
          path: build/**
